name: 'Call Concord trigger'
description: 'GitHub Composite Action to trigger Concord process'
inputs:
  concord_url:
    description: 'The URL of the concord'
    required: true
  auth_token:
    description: 'The Concord API auth token'
    required: true
  event:
    description: 'The trigger event name'
    required: true
  payload:
    description: 'The trigger event payload'
    required: true
  retries:
    description: 'The number of retries for the request'
    required: false
    default: 3
  retry_delay:
    description: 'The delay in seconds between retry attempts'
    required: false
    default: 5000
runs:
  using: 'composite'
  steps:
    - name: Call Concord trigger
      shell: bash
      run: |
        ${{ github.action_path }}/send-request.bash ${{ inputs.concord_url }} ${{ inputs.authToken }} ${{ inputs.event }}
