name: My Workflow
on:
  workflow_dispatch:

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: K8s concord payload
        shell: bash
        id: concord-payload
        run: |
          ACTION_LINK='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          PAYLOAD=''
          PAYLOAD='{"source": {"link": "$ACTION_LINK"}, "components": [{"name": "XXX", "repository": "YYY", "tag": "ZZZ"}]}'
          echo "$PAYLOAD"
