name: My Workflow
on:
  workflow_dispatch:

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          concord_url: ${{ secrets.CONCORD_URL }}
          auth_token: ${{ secrets.CONCORD_AUTH }}
          request_body: '{"message": "Hello!"}'
          retries: 3
          retry_delay: 10000
